# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ template "hbase.fullname" . }}-rs
  labels:
    app: {{ template "hbase.name" . }}
    chart: {{ include "hbase.chart" . }}
    
    heritage: {{ .Release.Service }}
    component: hbase-rs
spec:
  clusterIP: "None"
  ports:
  - port: 16020
    name: rs
  - port: 16030
    name: rsinfo
  selector:
    app: {{ template "hbase.name" . }}
    
    component: hbase-rs
