{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "loki.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      name: {{ template "loki.fullname" . }}
      app: {{ template "loki.name" . }}
      
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ template "client.name" . }}
            
    - ports:
      - port: {{ .Values.service.port }}
{{- end }}
